apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: apache-server
spec:
  selector:
    app: apache
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Choose an available port in the range 30000-32767
