apiVersion: v1
kind: Service
metadata:
  name: image-wala-service
  namespace: webserver
spec:
  selector:
    app: nginx-docker-wala
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082 # Choose an available port in the range 30000-32767